[package]
name = "pay_the_piper"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
solana-client = "1.14.13"
solana-sdk = "1.14.13"
spl-token = "3.5.0"
solana-account-decoder = "1.14.13"